  
# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ TER ]
  pull_request:
    branches: [ TER ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B clean install sonar:sonar -Dsonar.projectKey=Vamos -Dsonar.host.url=http://fpout.re:9000 -Dsonar.login=65a420ac03ad03c5bf893df759cb3f9c56c6ab74
